### ISSUE TITLE
[Port request] GP2Xpectrum

### ISSUE THREAD

**Issue by salvacam** [steward-fu/gh_retrogame_emulator#84]
Request port (GP2Xpectrum)
[http://dl.openhandhelds.org/cgi-bin/dingoo.cgi?0,0,0,0,46,121](url)

**Comment by steward-fu** [comment]
Since the emulator you mentioned is for ARM-base CPU only, I port speccy to RetoGame.
speccy emulator is also spectrum emulator for GCW0.
I load rom for testing, it works but sincce I have not play this emulator yet so far, if you can help to check it.
It is good.

put under ("/mnt/game/speccy/")
https://drive.google.com/file/d/1LcuXEv4z6sIpQrmodKVtUfzZk7mhudkl/view?usp=sharing

This emulator wll also be included in next release.
Thanks
